[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_ASSET_PREFIX = "/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects für alte Portfolio-URLs
[[redirects]]
  from = "/portfolio/munich-yoga"
  to = "/portfolio"
  status = 301

[[redirects]]
  from = "/portfolio/green-garden"
  to = "/portfolio"
  status = 301

[[redirects]]
  from = "/portfolio/city-share"
  to = "/portfolio/cityshare"
  status = 301

[[redirects]]
  from = "/portfolio/eco-cosmetics"
  to = "/portfolio"
  status = 301

# Wichtige Redirects für statische Assets
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = false

# Optimize cache management for static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
