[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NEXT_PUBLIC_ASSET_PREFIX = "/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Wichtige Redirects für statische Assets
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image/:splat"
  status = 200
  force = true

# Optimize cache management for static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
